In [1]:
from dataset_generator import generate_sample

X, y = generate_sample()

print("X:", X)
print("y:", y)
print("Shapes:", X.shape, y.shape)


X: [-2.86752961e+00  2.24657871e-01  5.98253508e-01  1.22108769e-01
  2.75974830e-03  6.91963589e-03  6.66273171e+02  5.04122051e+01
  1.27000000e+02  1.87791938e+02  1.75894465e+01  4.31668320e+01]
y: [1.82950828 0.42906369]
Shapes: (12,) (2,)


In [2]:
from dataset_generator import generate_dataset, save_dataset, generate_sample

X, y = generate_sample()
print(X.shape)
print(X)



(12,)
[-2.57504828e+00  1.18441053e-01  3.33813625e-01  1.19201202e-01
  2.30431845e-03  6.35831176e-03  6.25394309e+02  4.43224856e+01
  1.03100000e+02  1.86075530e+02  1.52710606e+01  3.77830629e+01]


In [3]:

X, y = generate_dataset(N=200, seed=42)

print("X shape:", X.shape)
print("y shape:", y.shape)

save_dataset(X, y, filename="dataset_mc_ml_v1.npz")



Generated 200/200
X shape: (200, 12)
y shape: (200, 2)


(array([[-2.43151287e+00,  1.31540710e-01,  3.34575345e-01, ...,
          2.55060954e+02,  2.09758997e+01,  5.41770215e+01],
        [-2.48490486e+00,  9.55195454e-02,  2.50774736e-01, ...,
          1.96182684e+02,  1.50354594e+01,  3.89839160e+01],
        [-2.67267465e+00,  1.83892978e-01,  4.83743488e-01, ...,
          2.51335915e+02,  1.86209725e+01,  4.78967717e+01],
        ...,
        [-2.91253446e+00,  2.34633402e-01,  6.12498015e-01, ...,
          1.63235460e+02,  1.50890690e+01,  4.04226424e+01],
        [-2.78940750e+00,  2.21923491e-01,  5.35566448e-01, ...,
          2.19052974e+02,  1.75543999e+01,  4.67624272e+01],
        [-2.33099189e+00,  9.80672911e-02,  2.40617698e-01, ...,
          2.56592188e+02,  1.68890699e+01,  4.33239836e+01]],
       shape=(200, 12)),
 array([[1.88991754, 0.68971578],
        [1.30254723, 0.58676149],
        [1.1937412 , 0.38918267],
        [1.68177259, 0.64286617],
        [0.71230729, 0.69596244],
        [1.03062524, 0.64289745],
 

In [4]:
import numpy as np

data = np.load("dataset_mc_ml_v1.npz")
X = data["X"]
y = data["y"]
print(X.shape)
print(X[:3])
print(y[:3])


(200, 12)
[[-2.43151287e+00  1.31540710e-01  3.34575345e-01  1.14095143e-01
   2.36584003e-03  6.51253586e-03  8.38120325e+02  5.76503633e+01
   1.53100000e+02  2.55060954e+02  2.09758997e+01  5.41770215e+01]
 [-2.48490486e+00  9.55195454e-02  2.50774736e-01  1.17354986e-01
   2.09386214e-03  5.51243487e-03  6.48542276e+02  4.45468539e+01
   1.13000000e+02  1.96182684e+02  1.50354594e+01  3.89839160e+01]
 [-2.67267465e+00  1.83892978e-01  4.83743488e-01  1.16840844e-01
   2.26233936e-03  5.83394957e-03  8.69031707e+02  5.12688416e+01
   1.33000000e+02  2.51335915e+02  1.86209725e+01  4.78967717e+01]]
[[1.88991754 0.68971578]
 [1.30254723 0.58676149]
 [1.1937412  0.38918267]]
